name: GitHub Actions Build and Test
on:
  push:
    branches: [test]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install bats
        run: |
         git clone git@github.com:bats-core/bats-core.git
         sudo ./bats-core/install.sh
      - name: Check bats version
        run: bats --version
      - name: Run bats script
        run: bats test.bats -F junit
      
