name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install xmllint
        run: sudo apt-get install -y bats
      - name: Chech bats version
        run: bats --version
      - name: Run bats script
        run: bats test.bats
      